### ISSUE TITLE
Issue with build 

### ISSUE THREAD

**Issue by BeardMatt** [geerlingguy/obs-task-list-overlay#6]
I'm using docker and went through your process and cannot get the container to load. it crashes with this error (below)

I even tried adding RUN npm install express to the dockerbuild file and made a second image and it still had the same error. Ideas?

internal/modules/cjs/loader.js:934

  throw err;
  ^
Error: Cannot find module 'express'
Require stack:
- /usr/src/app/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/usr/src/app/server.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/src/app/server.js' ]
}

**Comment by BeardMatt** [comment]
:(

**Comment by BeardMatt** [comment]
Friend?

**Comment by geerlingguy** [comment]
Sorry, I haven't used this project in a while; I will likely take a look again next time I need to use it but I don't know when that will be.
